global:
  scrape_interval:     10s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 15 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: 'bbc-stats'
    static_configs:
    - targets: ['192.168.56.200:4444']
