{
 "title": "Billionaire Buyers Club",
 "description": "Billionaire Buyers Club Dashboard",
 "tags": [ "cncf" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "How many yacht models are on sale",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "cncfdemo_stock_yachts" }
   ]
  },
  {
   "title": "How many plane models are on sale",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "cncfdemo_stock_planes" }
   ]
  },
  {
   "title": "How many car models are on sale",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "cncfdemo_stock_cars" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 0 },
   "content": "\n# Billionaire Buyers Club\n\nProudly brought to you by Oracle Linux SC Team.\n\nSource Code: [https://github.com/olsc-devops/bbc](https://github.com/olsc-devops/bbc)\n\n**Note: We are not going to deliver any of the stuff you bought!!!**\n\n\n\n"
  },
  {
   "title": "Stock counts",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "cncfdemo_stock_cars",
     "legendFormat": "How many cars are left in stock"
    },
    {
     "expr": "cncfdemo_stock_planes",
     "legendFormat": "How many planes are left in stock"
    },
    {
     "expr": "cncfdemo_stock_yachts",
     "legendFormat": "How many yachts are left in stock"
    }
   ]
  },
  {
   "title": "Total value of all transactions ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 5 },
   "targets": [
    { "expr": "cncfdemo_salesvalue" }
   ]
  },
  {
   "title": "Cash flow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    { "expr": "cncfdemo_salesvalue" }
   ]
  },
  {
   "title": "Number of transactions",
   "type": "graph",
   "description": "Number of all transactions",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cncfdemo_numberofsales" }
   ]
  }
 ]
}